#!/bin/bash

# Some parts of this script should run with sudo, others not
if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

if [ -n "$SUDO_USER" ]; then 
	true_user=$SUDO_USER
	nonroot_cmd="sudo -u $true_user "
else
	true_user=$(whoami)
	nonroot_cmd=""
fi

cd "$(dirname "$0")"

# jc42 driver will load automatically
echo -n "jc42 0x1f" > /sys/bus/i2c/devices/i2c-0/new_device

# or we could have just modprobe jc42, which would automatically find it too.

