#!/bin/bash

# Some parts of this script should run with sudo, others not
if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

if [ -n "$SUDO_USER" ]; then 
	true_user=$SUDO_USER
	nonroot_cmd="sudo -u $true_user "
else
	true_user=$(whoami)
	nonroot_cmd=""
fi

cd "$(dirname "$0")"

echo "install i2c-tools to configure ERTC"
yum -y install i2c-tools

echo "load I2C-dev"
modprobe i2c-dev

echo "load intel i2c driver (probably already loaded)"
modprobe i2c-i801

bus=`i2cdetect -l | grep -i i801 | cut -f1`
echo "Using i2c bus: $bus"

echo rx8581 0x32 | sudo tee /sys/bus/i2c/devices/$bus/new_device

sleep 1

if [ -c /dev/rtc1 ]; then
	echo "Linking /dev/rtc to ERTC"
	ln -sf /dev/rtc1 /dev/rtc

	echo "Done!"
	ls -l /dev/rtc*
else
	echo "could not find /dev/rtc1"
	echo "maybe something went wrong?"
	dmesg | tail
	ls -l /dev/rtc*
fi


